name: Publish

on:
  pull_request:
    types:
      - closed
    branches:
      - master

  # if testing is required (create branch called ci-updates)
  push:
    branches:
      - ci-updates

permissions:
  id-token: write # Required for OIDC authentication (workload identity provider)
  contents: read # Required to read the repo content

env:
  CI_DOCKER_IMAGE_NAME: "hello-world-example"

jobs:
  publish:
    name: Publish
    uses: "joepk90/serverless-apps-ci-workflows/.github/workflows/shared-publish.yaml@main"
    secrets: inherit
