name: Publish

on:
  pull_request:
    types:
      - closed
    branches:
      - master

  # if testing is required (create branch called ci-updates)
  push:
    branches:
      - ci-updates

jobs:
  publish:
    name: Publish
    uses: "joepk90/serverless-apps-ci-workflows/.github/workflows/shared-publish.yaml@main"
    secrets: inherit
